version: '2'

services:
  database:
    image: mongo:4.4.6
    volumes:
      - ./.data/db:/data/db
    command: mongod --port 27019
    ports:
        - 27019:27019
  redis:
    image: redis
    ports:
        - 6379:6379