basePath: /
definitions:
  CreateFieldRequest:
    properties:
      data:
        type: object
      name:
        type: string
      primitive:
        type: string
    required:
    - name
    - primitive
    type: object
  CreateSchemaRequest:
    properties:
      name:
        type: string
    type: object
  LoginRequest:
    properties:
      email:
        example: test@test.com
        type: string
      password:
        example: test
        type: string
    required:
    - email
    - password
    type: object
  LoginResponse:
    properties:
      jwt:
        type: string
      user:
        $ref: '#/definitions/user.Entity'
    type: object
  MeResponse:
    properties:
      jwt:
        type: string
      user:
        $ref: '#/definitions/user.Entity'
    type: object
  RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  RegisterResponse:
    properties:
      jwt:
        type: string
      user:
        $ref: '#/definitions/user.Entity'
    type: object
  http.createRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  press_core_field.Entity:
    properties:
      data:
        type: object
      id:
        type: string
      name:
        type: string
      primitive:
        type: string
      schemaId:
        type: string
    type: object
  press_core_schema_field.Entity:
    properties:
      data:
        type: object
      id:
        type: string
      name:
        type: string
      primitive:
        type: string
    type: object
  realm.Entity:
    properties:
      authorId:
        description: Fist iteration, a realm belongs only to one user.
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  schema.Entity:
    properties:
      fields:
        items:
          $ref: '#/definitions/press_core_schema_field.Entity'
        type: array
      id:
        type: string
      name:
        type: string
      realmId:
        type: string
    type: object
  user.Entity:
    properties:
      email:
        type: string
      id:
        type: string
    type: object
  util.HTTPError:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
host: localhost:5050
info:
  contact:
    name: API Support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
  title: GoPress
  version: "1.0"
paths:
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: Tries to login using some credentials.
      operationId: login
      parameters:
      - description: User login with email and password
        in: body
        name: body
        schema:
          $ref: '#/definitions/LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User response and JWT
          schema:
            $ref: '#/definitions/LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.HTTPError'
      summary: Tries to login using some credentials.
      tags:
      - Auth
  /v1/auth/register:
    post:
      consumes:
      - application/json
      description: Registers a new user with email and password
      operationId: register-user
      parameters:
      - description: User registration parameters
        in: body
        name: body
        schema:
          $ref: '#/definitions/RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User response and JWT
          schema:
            $ref: '#/definitions/RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.HTTPError'
      summary: Registers a new user with email and password
      tags:
      - Auth
  /v1/realm:
    get:
      consumes:
      - application/json
      description: Gets all the realms accessible for the current user
      operationId: get-realms
      produces:
      - application/json
      responses:
        "200":
          description: Realms to which the current user has access
          schema:
            items:
              $ref: '#/definitions/realm.Entity'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Gets all the realms accessible for the current user
      tags:
      - Realm
    post:
      consumes:
      - application/json
      description: Creates a new realm
      operationId: create-realm
      parameters:
      - description: Realm parameters
        in: body
        name: body
        schema:
          $ref: '#/definitions/http.createRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Creates a new realm
      tags:
      - Realm
  /v1/realm/{realmId}/schema:
    post:
      consumes:
      - application/json
      description: Creates a new schema
      operationId: create-schema
      parameters:
      - description: ??
        in: path
        name: realmId
        type: string
      - description: Schema parameters
        in: body
        name: body
        schema:
          $ref: '#/definitions/CreateSchemaRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.Entity'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Creates a new schema
      tags:
      - Schema
  /v1/realm/{realmId}/schema/{schemaId}/field:
    get:
      consumes:
      - application/json
      description: Gets all the fields of the given schema
      operationId: get-fields
      parameters:
      - description: Realm ID
        in: path
        name: realmId
        type: string
      - description: Schema ID
        in: path
        name: schemaId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/press_core_field.Entity'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Gets all the fields of the given schema
      tags:
      - Field
    post:
      consumes:
      - application/json
      description: Creates a new field
      operationId: create-field
      parameters:
      - description: Realm ID
        in: path
        name: realmId
        type: string
      - description: Schema ID
        in: path
        name: schemaId
        type: string
      - description: Field parameters
        in: body
        name: body
        schema:
          $ref: '#/definitions/CreateFieldRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/press_core_field.Entity'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Creates a new field
      tags:
      - Field
  /v1/user/me:
    get:
      consumes:
      - application/json
      description: Gets the current user and JWT
      operationId: me
      produces:
      - application/json
      responses:
        "200":
          description: User and JWT
          schema:
            $ref: '#/definitions/MeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Gets the current user and JWT
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
