basePath: /
definitions:
  LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  LoginResponse:
    properties:
      jwt:
        type: string
      user:
        $ref: '#/definitions/user.Entity'
    type: object
  RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  user.Entity:
    properties:
      email:
        type: string
      id:
        type: string
    type: object
host: localhost:5050
info:
  contact:
    name: API Support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
  title: GoPress
  version: "1.0"
paths:
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: Tries to login using some credentials.
      operationId: login
      parameters:
      - description: User login with email and password
        in: body
        name: body
        schema:
          $ref: '#/definitions/LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User response and JWT
          schema:
            $ref: '#/definitions/LoginResponse'
      security:
      - ApiKeyAuth: []
      summary: Tries to login using some credentials.
  /v1/auth/register:
    post:
      consumes:
      - application/json
      description: Registers a new user with email and password
      operationId: register-user
      parameters:
      - description: User registration parameters
        in: body
        name: body
        schema:
          $ref: '#/definitions/RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Registers a new user with email and password
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
